# config

x-service: &service
  image: node:21-alpine
  restart: always
  user: root
  working_dir: /home/app
  entrypoint: yarn
  command: dev
  dns:
    - 8.8.8.8
  expose:
    - 8000
  environment:
    - PORT=8000
    - APP_ENV=local
    - NODE_ENV=local
    - TZ=America/Sao_Paulo


services:

  # apps

  api:
    <<: *service
    volumes:
      - .:/home/app
    ports:
      - "8000:8000"

  # dependencies

  minio:
    image: bitnami/minio:latest
    volumes:
      - minio_data:/bitnami/minio/data 
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_FORCE_NEW_KEYS: yes
      MINIO_SCHEME: http
      MINIO_DEFAULT_BUCKETS: fshortner
      MINIO_ROOT_USER: fshortner
      MINIO_ROOT_PASSWORD: thisissecret

  redis:
    image: "redis:alpine"

  mockbin:
    image: ghcr.io/kong/insomnia-mockbin
    ports:
      - "8080:8080"
    environment:
      DEBUG: mockbin
      MOCKBIN_PORT: 8080
      MOCKBIN_REDIS: redis://redis:6379


volumes:
  minio_data: {}